/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BudgetResponse { 
    id?: number | null;
    amount?: number;
    month?: string | null;
    category_id?: number | null;
    is_recurring?: boolean;
    category_name?: string | null;
}

