/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CategoryModelInput { 
    id?: number | null;
    name?: string;
    description?: string;
    is_system?: boolean;
}

