/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DashboardSummary { 
    total_expenses: string;
    monthly_expenses: string;
    budget: string;
    budget_remaining: string;
    transactions: number;
}

