/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MonthlyExpense } from './monthlyExpense';
import { CategoryExpense } from './categoryExpense';
import { DashboardSummary } from './dashboardSummary';
import { RecentExpense } from './recentExpense';


export interface DashboardResponse { 
    summary: DashboardSummary;
    monthly_expenses: Array<MonthlyExpense>;
    category_expenses: Array<CategoryExpense>;
    recent_expenses: Array<RecentExpense>;
}

