/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExpenseModel { 
    id?: number | null;
    amount?: number;
    description?: string;
    categoryId?: number;
    sourceId?: number;
    merchantId?: number;
    transactionDate?: string;
}

