/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExpenseModel } from './expenseModel';


export interface ExpenseResponse { 
    total?: number;
    page?: number;
    page_size?: number;
    data?: Array<ExpenseModel>;
}

