/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExpenseModel { 
    id?: number | null;
    withdrawal?: number;
    deposit?: number;
    description?: string;
    category_id?: number;
    category_name?: string;
    sourceId?: number;
    merchantId?: number;
    transaction_date?: string;
}

