/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TransactionModel { 
    id: number;
    date?: string | null;
    category_id?: number;
    category_name?: string;
    description?: string | null;
    withdrawal?: number | null;
    deposit?: number | null;
}

